spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/solitiare?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false
    username: solitiare
    password: solitiare
server:
  port: 8088

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true